language: node_js

node_js:
  - 'stable'

branches:
  only:
    - master
    - develop

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

jobs:
  include:
    - stage: test
      name: test
      script:
        - yarn lint:ts
        - yarn lint:styles
        - yarn test
