name: 'CI'

on:
  pull_request:
    branches: [master, develop]

jobs:
  test_pull_request:
    runs-on: node:10.15.1-slim
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - run: yarn test
